-- Check what views and tables exist in the database
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE (TABLE_TYPE = 'BASE TABLE' OR TABLE_TYPE = 'VIEW')
    AND (TABLE_NAME LIKE '%Sales%' OR TABLE_NAME LIKE '%Order%' OR TABLE_NAME LIKE '%Product%')
ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME;

-- Alternative: Check ALL views and tables
-- SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES ORDER BY TABLE_TYPE, TABLE_NAME;
